spring.application.name=FlexShop
server.port=8080

# Database Configuration (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FlexShop_V2_Full;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# JWT Configuration (US-02: Access Token 15 mins, Refresh Token 7 days)
flexshop.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351
flexshop.jwt.access-token-expiration-ms=900000
flexshop.jwt.refresh-token-expiration-ms=604800000

# Thymeleaf & MVC
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Gmail SMTP Configuration (US-03)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duydkth05056@gmail.com
spring.mail.password=cbkm njas vjdm aipx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Cấu hình tải lên ảnh đại diện & tệp tin (US-04)
flexshop.upload.dir=uploads/avatars
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
