spring.application.name=FlexShop

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FlexShop_V2_Full;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sa

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# Multipart File Upload (Ảnh và Video bằng chứng)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Upload Directory
app.upload.dir=uploads/khieu-nai/

